spring:
  application:
    name: admin-server
server:
  port: 9301

eureka:
  client:
    register-with-eureka: true  #是否注册到注册中心
    fetch-registry: true  #是否获取注册中心实例列表
    service-url:
      defaultZone: http://localhost:8001/eureka/  #配置注册中心地址