server:
  port: 9201
service-url:
  user-service: http://localhost:8201

spring:
  cloud:
    gateway:
      routes:
        - id: path_route #\u8DEF\u7531\u7684ID,\u4E0D\u53EF\u4EE5\u91CD\u590D
          uri: ${service-url.user-service}/user/{id} #\u5339\u914D\u540E\u8DEF\u7531\u5730\u5740
          predicates: # \u65AD\u8A00\uFF0C\u8DEF\u5F84\u76F8\u5339\u914D\u7684\u8FDB\u884C\u8DEF\u7531,\u5373http://localhost:9021//user/1\u5C31\u8DEF\u7531\u5230uri
            - Path=/user/{id}
