server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true  #\u662F\u5426\u6CE8\u518C\u5230\u6CE8\u518C\u4E2D\u5FC3
    fetch-registry: true  #\u83B7\u53D6\u5B9E\u4F8B\u6CE8\u518C\u5217\u8868
    service-url:
      defaultZone: http://localhost:8001/eureka/  #\u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740

feign:
  hystrix:
    enabled: true #\u5728Feign\u4E2D\u5F00\u542FHystrix

#\u5F00\u542F\u65E5\u5FD7\u7684Feign\u5BA2\u6237\u7AEF
#\u914D\u7F6EUserService\u7684\u65E5\u5FD7\u7EA7\u522B\u4E3Adebug
logging:
  level:
    com.gbques.ly.cloud.feignservice.service.UserService: debug