server:
  port: 8201
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 0.1 #设置Sleuth的抽样收集概率



eureka:
  client:
    register-with-eureka: true #\u6CE8\u518C\u5230Eureka\u7684\u6CE8\u518C\u4E2D\u5FC3
    fetch-registry: true  #\u83B7\u53D6\u6CE8\u518C\u5B9E\u4F8B\u5217\u8868
    service-url:
      defaultZone: http://localhost:8001/eureka/  #\u914D\u7F6E\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
