server:
  port: 8206
spring:
  application:
    name: consul-user-service
  cloud:
    consul: #Consul\u670D\u52A1\u6CE8\u518C\u53D1\u73B0\u914D\u7F6E
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
